### ISSUE TITLE
Update build / README / CI to use west submanifest

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/gsoc-2022-thrift#139]
We should update build / README / CI to refer to the Zephyr Getting Started Guide and the very simple `submanifests/99-thrift.yaml`, shown below
```
manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: cfriedt
      url-base: https://github.com/cfriedt

  projects:
    - name: gsoc-2022-thrift
      path: modules/lib/thrift
      revision: main
    # This is actually a git submodule of gsoc-2022-thrift
    - name: thrift
      remote: cfriedt
      path: modules/lib/thrift/.upstream
      # corresponds to revision: v0.16.0, but the tag does not exist in cfriedt/thrift
      revision: 63cad2ee536ead54e6ac75fb5401beb9ab2bbee2
```

Setup instructions only really need to say, roughly: 
* follow the getting started guide
* create the file `submanifests/99-thrift.yaml` shown below
* run `west update`

We don't even need our own `zephyr-env.sh` in that case, nor do we need our own `west.yml` (although it may be handy to have).
